builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
#Configuration for building packages for rpm and deb package managers
nfpms:
  - package_name: coolie
    homepage: https://github.com/hmahdiany/coolie
    maintainer: Hossein Mahdiany <hossein.mahdiany@gmail.com>
    description: |-
            Pull container images from public registries and push them to private registries.
    formats:
      - rpm
      - deb